"""sync models

Revision ID: 2466c114399a
Revises: 
Create Date: 2025-08-11 15:56:07.525306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2466c114399a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_suggestions')
    op.add_column('comments', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('comments', sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'user_id')
    op.add_column('posts', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('posts', sa.Column('excerpt', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('category', sa.Text(), nullable=False))
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('posts', sa.Column('reading_time', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.alter_column('posts', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'readability_score')
    op.drop_column('posts', 'improved_content')
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'seo_keywords')
    op.add_column('users', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'name')
    op.add_column('posts', sa.Column('seo_keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('improved_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('readability_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_column('posts', 'reading_time')
    op.drop_column('posts', 'comments_count')
    op.drop_column('posts', 'likes_count')
    op.drop_column('posts', 'is_published')
    op.drop_column('posts', 'category')
    op.drop_column('posts', 'excerpt')
    op.drop_column('posts', 'author_id')
    op.add_column('comments', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'likes_count')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'author_id')
    op.create_table('topic_suggestions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trending', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('search_volume', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_suggestions_pkey'))
    )
    # ### end Alembic commands ###
