"""added new column to users

Revision ID: 71c287f1f985
Revises: c38e9a06d8c4
Create Date: 2025-08-17 10:16:00.327402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c287f1f985'
down_revision = 'c38e9a06d8c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'audio_url')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
