"""update models

Revision ID: c38e9a06d8c4
Revises: 2466c114399a
Create Date: 2025-08-16 10:46:11.319086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38e9a06d8c4'
down_revision = '2466c114399a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'excerpt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('posts', 'excerpt',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
